[build]
  base = "/timestamp"
  publish = "src/"
  functions = "lambda"
  command = "npm install && PUBLIC_URL=https://timestamp-microservice.netlify.app/ npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 301
