[build]
  base = "/timestamp"
  publish = "src/"
  functions = "lambda"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
